import { MacroConfig } from './types';

export const DEFAULT_MACROS: MacroConfig[] = [
  {
    id: 'macro-faucet-clicker',
    name: '⚡ Тапалка монет и сбор наград',
    description: 'Многократные клики по кнопке сбора наград с защитой от лагов сети и счетчиком кликов',
    targetUrl: '', // uses playground by default
    loopCount: 10,
    timingMode: 'adaptive',
    fixedIntervalMs: 600,
    randomJitterMs: 100,
    adaptiveSettings: {
      minDelayMs: 250,
      maxWaitElementMs: 4000,
      waitForDomReady: true,
      waitForNetworkIdle: true,
      speedMultiplier: 1.0,
    },
    steps: [
      {
        id: 'step-1',
        label: 'Тапнуть монету +1',
        action: 'click',
        selector: '#tap-coin-btn',
        enabled: true,
        customDelayMs: 400,
      },
      {
        id: 'step-2',
        label: 'Собрать бонусный бустер',
        action: 'click',
        selector: '#claim-bonus-btn',
        enabled: true,
        customDelayMs: 600,
      },
    ],
    createdAt: Date.now() - 3600000,
    updatedAt: Date.now() - 3600000,
  },
  {
    id: 'macro-form-order',
    name: '📝 Авто-заполнение формы и оформление',
    description: 'Последовательный ввод email, выбора товара, согласия с правилами и нажатия кнопки отправки',
    targetUrl: '',
    loopCount: 1,
    timingMode: 'fixed',
    fixedIntervalMs: 800,
    randomJitterMs: 150,
    adaptiveSettings: {
      minDelayMs: 300,
      maxWaitElementMs: 5000,
      waitForDomReady: true,
      waitForNetworkIdle: false,
      speedMultiplier: 1.0,
    },
    steps: [
      {
        id: 'step-form-1',
        label: 'Ввод Email',
        action: 'type',
        selector: '#input-user-email',
        textValue: 'trader@autoclick.io',
        enabled: true,
        customDelayMs: 500,
      },
      {
        id: 'step-form-2',
        label: 'Ввод Промокода',
        action: 'type',
        selector: '#input-promo-code',
        textValue: 'SPEED2026',
        enabled: true,
        customDelayMs: 600,
      },
      {
        id: 'step-form-3',
        label: 'Активировать промокод',
        action: 'click',
        selector: '#apply-promo-btn',
        enabled: true,
        customDelayMs: 800,
      },
      {
        id: 'step-form-4',
        label: 'Выбрать опцию Быстрой доставки',
        action: 'click',
        selector: '#shipping-fast-radio',
        enabled: true,
        customDelayMs: 400,
      },
      {
        id: 'step-form-5',
        label: 'Подтвердить заказ',
        action: 'click',
        selector: '#submit-order-btn',
        enabled: true,
        customDelayMs: 1000,
      },
    ],
    createdAt: Date.now() - 1800000,
    updatedAt: Date.now() - 1800000,
  },
  {
    id: 'macro-tab-crawler',
    name: '🔄 Циклический обход вкладок и сбор данных',
    description: 'Поочередное переключение вкладок с ожиданием загрузки содержимого перед кликом',
    targetUrl: '',
    loopCount: 3,
    timingMode: 'adaptive',
    fixedIntervalMs: 1200,
    randomJitterMs: 200,
    adaptiveSettings: {
      minDelayMs: 500,
      maxWaitElementMs: 6000,
      waitForDomReady: true,
      waitForNetworkIdle: true,
      speedMultiplier: 1.0,
    },
    steps: [
      {
        id: 'step-tab-1',
        label: 'Вкладка "Статистика"',
        action: 'click',
        selector: '#tab-btn-stats',
        enabled: true,
        customDelayMs: 700,
      },
      {
        id: 'step-tab-2',
        label: 'Обновить график',
        action: 'click',
        selector: '#refresh-chart-btn',
        enabled: true,
        customDelayMs: 900,
      },
      {
        id: 'step-tab-3',
        label: 'Вкладка "Заказы"',
        action: 'click',
        selector: '#tab-btn-orders',
        enabled: true,
        customDelayMs: 700,
      },
      {
        id: 'step-tab-4',
        label: 'Скачать отчет',
        action: 'click',
        selector: '#export-data-btn',
        enabled: true,
        customDelayMs: 1000,
      },
    ],
    createdAt: Date.now() - 900000,
    updatedAt: Date.now() - 900000,
  },
];
